### DISCUSSION TITLE
On partition filters, parameters and use cases.

### DISCUSSION THREAD

**Discussion by agorajek** [DataJunction/dj#421] [Ideas]
My goal here is to make us think about these ^ ideas and how useful or necessary they are in the early days of DJ. I was wondering if I should add my thoughts to https://github.com/DataJunction/dj/discussions/407 because they are related, but I wanted to highlight the filter/parameter side of things here.

**Use cases**:
1. Full or incremental (any cadence) materialization of nodes.
2. Custom materialization with partition filters.
3. Querying of nodes with partition filters.

Let's **consider a transform node**:
```yaml
node:
  type: transform
  name: t1
  sql: ...

  schema:
    user_id: int
    group_id: int
    date_int: int
    ...

  partitions:
    group_id:
       temporal: false
       required: true
    date_int:
       temporal: true    
  
  materialization:
    schedule: daily|hourly|weekly|etc  # or cron spec
    partitions:
      # partition_column: DJ query or expression
      date_int: CAST(FORMAT(NOW(), "YYYMMDD") AS INT)
      group_id: SELECT some_column FROM some_node WHERE ... # or simply `node.column`

  availability_state:
    vtts: ...
    min_partition: ...
    max_partition: ...
    partitions:
      # keyed on a list of all required partitions
      ["12345"]: (<vtts>, <min_partition>, <max_partition>) 
      ["54321"]: (<vtts>, <min_partition>, <max_partition>)
      ...
```

The above model has all we need to build materialization jobs and to require the query builder to provide (or ask the user for) values for the required partition filters. 

I could think of addition `parameters` section at the node level that would not need to be tied to the partition columns (in any way) but this seems like a nice-to-have option that can be added later on (if at all at this level).
```yaml
  parameters:
    <parameter-name>:
      type: int
```

**Some related questions**:
1. What other use case should be considered here?
2. Partitioning strategy is usually common across all/most tables in a given system. It would be good to provide global default settings for partitions, materialization or other aspects of the nodes. This would be not only a convenience feature but also a good standardization strategy.

**Comment by agorajek** [comment]
After some discussion with @shangyian this morning we concluded that (in the short term) we should focus on the materialization use case wrt parameters and partitions. The use case of live querying data is separate and we can address that later.

We concluded that:
1. Parameters should only be defined on partition columns.
2. And that initially we should only allow simple parameter/partition conditions (value, list, range) which would be specified by the user during scheduling a materialization call, example:

```
  materialization:
    schedule: @daily
    partitions:
      date_int: 
        value: CAST(FORMAT(NOW(), "YYYMMDD") AS INT) # must evaluate to <same type as date_int>
        list: None
        range: (None, None)
      group_id: 
        value: None
        list: [123, 234, 345, 456] # must evaluate to ARRAY[<same type as group_id>]
        range: (None, None)
```

Few more thoughts on this:
1. This makes me think that the materialization schedule could potentially be defined with a list of specs, not just one spec. And we can make sure (down the road) during the scheduling API call that the values are non-overlapping for the non-temporal partitions. 
2. This pattern should also allow for running backfill-in-place and keep track of it whether it was created by a user or by the Materialization Service (notice that backfills-on-the-side are always doable anyway).
3. Since we want to allow materialization params to be tied to partitions we don't have a problem of tracking multiple tables. 
4. About Druid... we already consider generating cubes as a step-after-materialization-in-iceberg (correct?) so with that in mind we could add a special (or similar) availability state on the Cube nodes to represent the sets of partitions/dimensions materialized and copied to Druid. Let's talk about it...
